### PR TITLE
feat: inline images in report html

### PR DESCRIPTION
**Pull request by jkroepke**
Ref: https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/issues/41#issuecomment-2176032450

Avoid FS access for an chrome

### CODE REVIEW

**Comment by mahendrapaipuri** [comment]
Thanks again for this work. We are in right direction. However, we can even improve this further to remove the dependence on file system entirely. For instance, [here](https://github.com/jkroepke/grafana-dashboard-reporter-app/blob/44e6305583d7006184cfc98a855e17d436fde667/pkg/plugin/report.go#L228-L246) we are saving the PNGs to file system. Instead of doing that, we can convert the PNG bytes to base64 encodings and save them on `Panel` struct directly. In case we must [pass pointer to `Dashboard` and `Panel`](https://github.com/jkroepke/grafana-dashboard-reporter-app/blob/44e6305583d7006184cfc98a855e17d436fde667/pkg/plugin/report.go#L222). Then, inside the template, we have directly base64 encodings available for each panel PNG and we embed them directly in HTML. 

Does it make sense?

**Comment by jkroepke** [comment]
> For instance, [here](https://github.com/jkroepke/grafana-dashboard-reporter-app/blob/44e6305583d7006184cfc98a855e17d436fde667/pkg/plugin/report.go#L228-L246) we are saving the PNGs to file system.

Sure, good idea for an follow-up PR!

**Comment by jkroepke** [comment]
so after reading the [best practices](https://grafana.com/developers/plugin-tools/get-started/best-practices#backend-plugins) of an grafana app, it clearly says don't work with local file system.

Based on that, I also avoid fs access for png and html report as well.

**Comment by mahendrapaipuri** [comment]
> so after reading the [best practices](https://grafana.com/developers/plugin-tools/get-started/best-practices#backend-plugins) of an grafana app, it clearly says don't work with local file system.

Exactly, that was the reason I wanted to completed avoid FS access.

This is awesome work. Thanks a lot. There is still some cleaning up to do but I will do it up in a separate PR. I will merge this now.

**Pull request merged**
