### PR TITLE
feat: allow custom templates

### LINKED ISSUE #19: Modifying the output of generated report
Hi @mahendrapaipuri,

Is there a way to modify the output ? 

For example, the number of page is present at the bottom of each page and in the dashboard title.

Regards

### PR DESCRIPTION
**Pull request by jkroepke**
Fixed #19

### CODE REVIEW

**Comment by PAPAMICA** [comment]
Good work !

I need this feature, can you merge please? 

Have a nice day!

**Comment by mahendrapaipuri** [comment]
@PAPAMICA Cheers for your interest. If I may ask, what exactly you would like to override in the default template? This helps us to better design this feature.

We are in the process doing a huge refactor of the plugin so it will take a while before we can merge this. I have just relaunched CI and you should be able to get plugin artifacts after the CI run to use for your deployment if you need it right away.

**Comment by vlzobov** [comment]
@mahendrapaipuri We're also interested in this feature. Team wants to use plugin, but wants report with customized styles and format.

As example one of the requirements: each row with it's panels should be on separate report page. (I'm not sure that is even possible, but that's what team want.) 

As you mentioned a huge refactor, so when we can expect to have next release?

**Comment by jkroepke** [comment]
> huge refactor

https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/pull/52 - At least the refactoring is already in review.

**Comment by mahendrapaipuri** [comment]
> As example one of the requirements: each row with it's panels should be on separate report page. (I'm not sure that is even possible, but that's what team want.)

This sort of fine grained control can be hard to achieve. As of now, I dont see a lot of value in allowing the custom template for the "body" of the report. The core plugin will fetch all the dashboard panels and estimate the coordinates of each panel in the report according to chosen config. 

We can easily allow the users to customize the header and footer of the report but the body, I dont see a easy way. @jkroepke Do you have any ideas?

Regarding #52, I will look into it this weekend. Cheers!!

**Comment by vlzobov** [comment]
Are custom templates already allowed in 1.5.0 release? If not, are you planning to include it next release?

**Comment by mahendrapaipuri** [comment]
Hey @vlzobov no not yet. I am waiting to merge a security related [PR](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/pull/86) before working on template customization. I am waitin for upstream Grafana to make few changes for the PR to work.

**Comment by mahendrapaipuri** [comment]
Hello @vlzobov Please check the main branch which supports custom templates now. I will make a release next week.

**Pull request closed without merging**
